version: "2.0"

services:

  server:
    build: server/
    command: ../npm install
    command: node server.js
    ports:
      - 3076:3076

  db:
    build: db/
    command: mongod --dbpath dataDB --port 1234
    ports:
      - 1234:1234

